### ISSUE TITLE
How would I customise activeEvents?

### ISSUE THREAD

**Issue by j4k** [noderaider/redux-idle-monitor#1]
I see the defaults, is there any easy way to extend them?

**Comment by cchamberlain** [comment]
@j4k - Sorry for the extremely long wait, I somehow missed this in my feed.

You should be able to override the defaults by passing in an array of activeEvents as an option:

The defaults it uses are `[ 'mousemove', 'keydown', 'wheel', 'DOMMouseScroll', 'mouseWheel', 'mousedown', 'touchstart', 'touchmove', 'MSPointerDown', 'MSPointerMove' ]`


To override you should be able to pass an array of `activeEvents` as an option:

```js
import configure from 'redux-idle-monitor'
import { idleStatusDelay, activeStatusAction, idleStatusAction } from './actions'

const opts =  { appName: 'todo-app'
              , IDLE_STATUSES
              , idleStatusDelay
              , activeStatusAction
              , idleStatusAction
              , activeEvents: [ 'mousemove' ]
              }

const { middleware, reducer, actions } = configure(opts)
```

**Comment by cchamberlain** [comment]
Going to add a blip about this to the README and close, please reopen if you have further questions.
