### ISSUE TITLE
Cannot use library behind corporate proxy

### ISSUE THREAD

**Issue by marekadamek** [noderaider/redux-idle-monitor#13]
Hello,

I'm using npm behind corporate proxy, thus I do not have access to gihub. I can see that some redux-idle-monitor are downloaded directly from github (please check the console output below). Would that be possible to fix dependencies to versions already released to https://registry.npmjs.org/

$ npm install
dff-react@0.0.1 C:\git\farefocus-app\react
`-- redux-idle-monitor@0.6.1
  `-- localsync@1.3.1
    +-- cookiesync@1.3.1
    | `-- react-cookie@0.4.6  (git://github.com/noderaider/react-cookie.git#eb419258badf89893595119d73b88ad6cd53e089)
    `-- socketsync@1.3.1
      `-- local-storage@1.4.1  (git://github.com/noderaider/local-storage.git#b9725b0fc77faabc737ba7c6ee57d343afa95102)

BR,
Marek Adamek

**Comment by cchamberlain** [comment]
Thanks for opening the issue! I'll get this pointing at the npm version and publish a new version tomorrow.

**Comment by cchamberlain** [comment]
@marekadamek - New version of `redux-idle-monitor` and `localsync` have been published with all dependencies pointing at npm. Going to close but please let me know if you have any more issues after running `npm i -S redux-idle-monitor@latest`.

**Comment by marekadamek** [comment]
Just verified and it works like a charm. Thanks a lot!
