### ISSUE TITLE
idle monitor state should have idle value

### ISSUE THREAD

**Issue by damiangreen** [noderaider/redux-idle-monitor#14]
I've set it up as described, with a few tweaks as i'm using https://github.com/davezuko/react-redux-starter-kit
I get this error continuously:
![image](https://cloud.githubusercontent.com/assets/1592820/24605780/176e9c84-1862-11e7-89c5-ac7bd0addaba.png)

And i don't see 'idle'  as a key in my state. 
The library seems to react to state changes however.

I also get No reducer provided for key "idle"
 at start

```
  const middleware = [thunk, idleMiddleware]`
....
const store = createStore(
    makeRootReducer(),
    initialState,
    composeEnhancers(
      applyMiddleware(...middleware),
      ...enhancers
    )
  )
```

reducers.js
```
import { combineReducers } from 'redux'
import locationReducer from './location'
import { reducer as idle } from 'redux-idle-monitor'

export const makeRootReducer = (asyncReducers) => {
  return combineReducers({
    location: locationReducer,
    idle: idle,
    ...asyncReducers
  })
}
```

**Comment by damiangreen** [comment]
doh. 
I figured it out, my Dux module was named the same as 'redux-idle-monitor' and I omitted the relative path './'

`import { reducer as idle } from './redux-idle-monitor'`

**Comment by cchamberlain** [comment]
@damiangreen happy to hear you got it figured out, please open another issue / PR if anything could have been more intuitive (better error messages, etc)!
