### ISSUE TITLE
Object doesn't support property or method 'includes' - IE11

### ISSUE THREAD

**Issue by damiangreen** [noderaider/redux-idle-monitor#16]
In context.js.

`return ['trace', 'debug', 'info'].includes(level) `

Is there a recommended polyfill to get this working with IE11?

**Comment by cchamberlain** [comment]
`core-js` or any polyfill with `Array.prototype.includes` should work.
Would also accept an ES5 PR if preferred.

**Comment by damiangreen** [comment]
brilliant. I wasn't aware of core-js before. it's done the trick.
 For future readers:

`require('core-js/fn/array/includes')`

**Comment by cchamberlain** [comment]
Thanks for reporting, I will probably rewrite that part when I get some time to not require polyfills for not often used logging.
