### ISSUE TITLE
Object.assign error on IE11

### ISSUE THREAD

**Issue by msell** [noderaider/redux-idle-monitor#2]
On IE11 I get an error when I use redux-idle-monitor _Object doesn't support property or method 'assign'_  I of coarse use Object assign in my redux app in other places with no issues, but when I wire up redux-idle-monitor IE11 has this error and does not load the page.

**Comment by cchamberlain** [comment]
I've been running this in a prod app with no issues on IE10+ but I suspect that is something to do with the global polyfills in my app.

I just built and published a new version using `babel-plugin-transform-runtime`, can you install latest and give it a shot?

**Comment by msell** [comment]
I just updated to the latest version, and same issue.  I will try to start a vanilla redux project tonight, and just incorporate the redux-idle-monitor and see if I still have IE issues.  Thanks so much for your work on this today, I'll do my part and even publish a sample project if I can reproduce it on a fresh application.

**Comment by msell** [comment]
OK I initialized a new project using redux-cli boilerplate which is the same boiler plate our enterprise app was started with and I just added redux-idle-monitor and it is working in IE. Here is the sample project I created to test it out https://github.com/msell/redux-idle-monitor-example.  If you navigate away from home page, then 5 seconds of inactivity will re-route you to root.   Feel free to consider this issue closed.  Thanks.
