### ISSUE TITLE
redux-blueprints and redux-mux have Chai as a dependency

### ISSUE THREAD

**Issue by Discordius** [noderaider/redux-idle-monitor#20]
It seems that both redux-blueprints and redux-mux have chai as a dependency. Here is the dependency graph `npm` printed out for me when I installed the package. 

```
└─┬ redux-idle-monitor@0.7.0
  ├─┬ localsync@1.4.0
  │ ├─┬ cookiesync@1.4.0
  │ │ └── react-cookie@1.0.4
  │ ├── serversync@1.4.0
  │ ├─┬ socketsync@1.4.0
  │ │ ├── local-storage@1.4.2
  │ │ └── react-cookie@1.0.4
  │ ├─┬ storagesync@1.4.0
  │ │ └── local-storage@1.4.2  deduped
  │ └── webrtcsync@1.4.0
  ├─┬ redux-actions@0.9.1
  │ ├─┬ flux-standard-action@0.6.1
  │ │ └─┬ lodash.isplainobject@3.2.0
  │ │   ├── lodash._basefor@3.0.3
  │ │   ├── lodash.isarguments@3.1.0
  │ │   └─┬ lodash.keysin@3.0.8
  │ │     ├── lodash.isarguments@3.1.0  deduped
  │ │     └── lodash.isarray@3.0.4
  │ └── reduce-reducers@0.1.2
  ├─┬ redux-blueprint@0.2.23
  │ ├─┬ chai@3.5.0
  │ │ ├── assertion-error@1.0.2
  │ │ ├─┬ deep-eql@0.1.3
  │ │ │ └── type-detect@0.1.1
  │ │ └── type-detect@1.0.0
  │ └── redux-actions@0.9.1  deduped
  ├─┬ redux-middleware@0.1.21
  │ ├── chai@3.5.0  deduped
  │ ├── redux-actions@0.9.1  deduped
  │ └── redux-blueprint@0.2.23  deduped
  └─┬ redux-mux@0.1.15
    └── chai@3.5.0  deduped
```

Chai is a pretty big package, and this seems to unnecessarily bloat the size of this package. Not sure what one can do about it.

**Comment by cchamberlain** [comment]
Thanks for opening. Going to reduce all dependencies to make this as slim as possible for the 1.0 release. This wasn't big on my radar for the early releases but has been the number one request I've seen.

**Comment by cchamberlain** [comment]
@Discordius just finished upgrading the `localsync` prong of this to TypeScript, reduced production dependencies to the minimum, and rolled `cookiesync`, `serversync`, and `storagesync` up into the main `localsync` package.

Deleted `webrtcsync` and `socketsync` altogether.

Its passing all unit tests (now on Jest) and published under `beta` tag. PR here - https://github.com/noderaider/localsync/pull/4

**Comment by cchamberlain** [comment]
@Discordius finished massive baseline TypeScript source upgrade to the following projects last night:
- `redux-idle-monitor`
- `localsync`
- `redux-blueprint`
- `redux-mux`

I've cut as many dependencies as possible and now they all use `invariant` instead of `chai` for assertions. I also found a couple of issues and fixed them.

Would love to get some feedback, I published everything under the `next` tag so you can install via:

```sh
yarn add redux-idle-monitor@next
# OR
npm install redux-idle-monitor@next
```

**Comment by Discordius** [comment]
Nice! I am currently traveling until the 25th, but will let you know how
the upgrade goes as soon as I am back.

**Comment by damiangreen** [comment]
has this broken anything?

I appear to be getting 

`PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at http://localhost:9877webpack:///~/redux-blueprint/lib/index.js:3:0 <- tests/test-bundler.js:134482`

Whcih appears to be referenced as an issue in the other repo

**Comment by cchamberlain** [comment]
@damiangreen I think the issue should be fixed now. Can you attempt running one of the following:

```
yarn add redux-idle-monitor@next
```

OR

```
npm install -S redux-idle-monitor@next
```

**Comment by damiangreen** [comment]
Just tried that and now i get 

`PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  Error: Cannot find module "tslib"
  at http://localhost:9877webpack:///~/redux-mux/lib/index.js:3:0 <- tests/test-bundler.js:137258`

**Comment by cchamberlain** [comment]
@damiangreen should be fixed now, I've published a versions of all the libraries, please reinstall `redux-idle-monitor@next`.

I incorrectly had `tslib` in `devDependencies` and it takes the place of `babel-polyfill` in the TypeScript version. Should fix https://github.com/noderaider/redux-blueprint/issues/2#issuecomment-345969897 as well.

**Comment by damiangreen** [comment]
looks like it's fixed ;)

**Comment by cchamberlain** [comment]
@damiangreen thanks for all your testing / feedback, its been crucial given I don't have a proper integration test right now - on roadmap for v2 to have one. Now that these are all on TypeScript with minimal build complexity, I'm confident I can add some of the requested features and get v2 out without breaking things.

The upgrade was mostly lift an shift but I did catch what I believe to be a bug in the idle monitoring. If you notice any changes, good or bad, I'd appreciate the feedback.

**Comment by damiangreen** [comment]
hiya, the upgrade has caused it to stop working in IE11. I've raised a separate ticket for this
