### ISSUE TITLE
Enable cross-tab support

### ISSUE THREAD

**Issue by mikeLspohn** [noderaider/redux-idle-monitor#25]
Are there any actions you have to take to enable cross-tab support? I have everything setup and it works in one tab fine, but opening a second tab they seem to not be aware of each other's events to reset the idle expiration. One will expire and the other is still inactive.

**Comment by mikeLspohn** [comment]
Actually, it seems to work fine now even though I didn't change anything. I would say this is safe to disregard.

**Comment by cchamberlain** [comment]
Thanks! Please reopen if you see any future weirdness!
