### ISSUE TITLE
Disable console info messages

### ISSUE THREAD

**Issue by stefanbaumg** [noderaider/redux-idle-monitor#5]
Is there any way to disable the console.info messages such as `idle | info: 'activity detection starting'` or `idle | info: 'Setting local tab to active'`?

**Comment by cchamberlain** [comment]
Sorry about that, I've been meaning to get to it. I will publish a release tomorrow.

**Comment by cchamberlain** [comment]
Published, should be fixed in `0.4.4`.

Default now is to only log on errors. There is an undocumented `level` string option that can be provided which lets you tailor to the common log levels (for debugging). I'll document the other options in the near future.

Thanks for reporting!

**Comment by stefanbaumg** [comment]
Wow, that was fast! Thanks!
