### ISSUE TITLE
getting error on console in every mouse move and active status action never fired

### ISSUE THREAD

**Issue by vivdkool** [noderaider/redux-idle-monitor#8]
idle monitor state should have idle value: expected undefined to exist

i have setup my project as explained in readme :( can you help me quickly...

**Comment by vivdkool** [comment]
i able to come out the problem i have given reducer name something else instead of 'idle'. is will be not good to provide custom name to reducer.

**Comment by vivdkool** [comment]
i have one question how to handle browser refresh?

i am using redux persist to persist my store...

**Comment by cchamberlain** [comment]
Per original question: as of right now, the `idle` redux key is hard coded. It would be trivial to make it configurable if this is a real problem for anyone and is likely something I'll add in a future version either way. Please let me know if it is keeping you from using it.

Regarding browser refresh, I'm using this in a production app without any issues. I'm not sure why redux persist would cause it to not work on refresh, but I have not personally used that library.

**Comment by vivdkool** [comment]
i don't know why its not working for me but i made it to work by starting again when persist is done.
i have another question i want to configured the time by making API call how we can do that is there any provision for that... ?

**Comment by cchamberlain** [comment]
You would have to set it up to not configure it until you've made that API call, or perhaps give it a default value and check to see if the API call value has returned yet. I'm on vacation ATM but I should be able to give an example next week if you need one.

**Comment by cchamberlain** [comment]
Closing, reopen if you have more questions.
