### ISSUE TITLE
Consider switching chai to invariant

### ISSUE THREAD

**Issue by jatwork** [noderaider/redux-idle-monitor#9]
Hi,

I'm in the process reviewing the bundle size of our web app and I found that `redux-idle-monitor` is taking `chai` as a [dependency][dep-in-package]. Wouldn't it be better if we switch to a more lightweight, production-ready package like [invariant][invariant]? What do you think?

I could help a PR to switch it over.

Thanks

[dep-in-package]: https://github.com/noderaider/redux-idle-monitor/blob/6ffe50f0d24b249478bfad1dca5bb3ff2a5e5407/package.json#L37
[invariant]: https://www.npmjs.com/package/invariant

**Comment by cchamberlain** [comment]
Thanks for the issue! I've started using invariant on other packages and would happily accept a PR that swaps it out.
